name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.build-gradle-project.outputs.upload_url }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build

  release_assets:
      name: Release assets
      needs: build-gradle-project
      runs-on: ubuntu-latest
      steps:
        # checkout of cource
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Upload release assets
          uses: actions/upload-release-asset@v3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.build-gradle-project.outputs.upload_url }}
            # This is how it will be named on the release page. Put hatever name
            # you like, remember that they need to be different for each platform.
            # You can choose any build matrix parameters. For Rust I use the
            # target triple.
            asset_name: rotv-1.20.1
            # The path to the file you want to upload.
            asset_path: ./build/libs/
            # probably you will need to change it, but most likely you are
            # uploading a binary file
            asset_content_type: application/octet-stream
